-- {"id":2,"version":"2.0.0","author":"Doomsdayrs","repo":""}

return Require("Madara")("https://boxnovel.com", {
	id = 2,
	name = "BoxNovel",
	imageURL = "https://boxnovel.com/wp-content/uploads/2018/04/BoxNovel-1.png",
	genres = {
		["action"] = "Action",
		["adventure"] = "Adventure",
		["comedy"] = "Comedy",
		["drama"] = "Drama",
		["ecchi"] = "Ecchi",
		["fantasy"] = "Fantasy",
		["gender-bender"] = "Gender Bender",
		["harem"] = "Harem",
		["historical"] = "Historical",
		["horror"] = "Horror",
		["josei"] = "Josei",
		["martial-arts"] = "Martial Arts",
		["mature"] = "Mature",
		["mecha"] = "Mecha",
		["mystery"] = "Mystery",
		["psychological"] = "Psychological",
		["romance"] = "Romance",
		["school-life"] = "School Life",
		["sci-fi"] = "Sci-fi",
		["seinen"] = "Seinen",
		["shoujo"] = "Shoujo",
		["shounen"] = "Shounen",
		["slice-of-life"] = "Slice of Life",
		["smut"] = "Smut",
		["sports"] = "Sports",
		["supernatural"] = "Supernatural",
		["tragedy"] = "Tragedy",
		["wuxia"] = "Wuxia",
		["xianxia"] = "Xianxia",
		["xuanhuan"] = "Xuanhuan",
		["yaoi"] = "Yaoi",
		["complete"] = "Completed",
		["on-going"] = "Ongoing",
		["canceled"] = "Canceled",
		["on-hold"] = "On Hold",
	},
	latestNovelSel = "div.col-xs-12.col-md-6"
})
