-- {"id":173,"version":"1.0.0","author":"TechnoJo4","repo":""}

return Require("Madara")("https://foxaholic.com", {
	id = 173,
	name = "Foxaholic",
	imageURL = "https://foxaholic.com/wp-content/uploads/2019/12/images-1.png",
	genres = {
		["action"] = "Action",
		["adventure"] = "Adventure",
		["bg"] = "BG",
		["bl"] = "BL",
		["chinese"] = "Chinese Novel",
		["comedy"] = "Comedy",
		["drama"] = "Drama",
		["ecchi"] = "Ecchi",
		["fantasy"] = "Fantasy",
		["gender-bender"] = "Gender Bender",
		["gl"] = "GL",
		["harem"] = "Harem",
		["historical"] = "Historical",
		["horror"] = "Horror",
		["isekai"] = "Isekai",
		["japanese"] = "Japanese Novels",
		["josei"] = "Josei",
		["martial-arts"] = "Martial Arts",
		["mature"] = "Mature",
		["mecha"] = "Mecha",
		["modern"] = "Modern",
		["mystery"] = "Mystery",
		["original"] = "Original Novel",
		["psychological"] = "Psychological",
		["quick-transmigration"] = "Quick Transmigration",
		["rebirth"] = "Rebirth",
		["romance"] = "Romance",
		["school-life"] = "School Life",
		["sci-fi"] = "Sci-fi",
		["seinen"] = "Seinen",
		["shoujo-2"] = "Shoujo",
		["slice-of-life"] = "Slice of Life",
		["supernatural"] = "Supernatural",
		["thai"] = "Thai Novel",
		["tragedy"] = "Tragedy",
		["transmigration"] = "Transmigration",
		["wuxia"] = "Wuxia",
		["xianxia"] = "Xianxia",
		["xuanhuan"] = "Xuanhuan"
	}
})
