-- {"id":736,"version":"1.0.0","author":"Doomsdayrs","repo":""}

local baseURL = "https://kisslightnovels.info"

return Require("Madara")(baseURL, {
	id = 736,
	name = "KissLightNovels",
	baseURL = baseURL,
	imageURL = "https://kisslightnovels.info/wp-content/uploads/2017/10/kisslightnovels-logo.png",
	latestNovelSel = "div.col-6.col-md-3",
	novelPageTitleSel = "h1",
	genres = {
		["a-novel"] = "17+",
		["action"] = "Action",
		["adventure"] = "Adventure",
		["comedy"] = "Comedy",
		["cooking"] = "Cooking",
		["detective"] = "Detective",
		["doujinshi"] = "Doujinshi",
		["drama"] = "Drama",
		["ecchi"] = "Ecchi",
		["fantasy"] = "Fantasy",
		["gender-bender"] = "Gender Bender",
		["harem"] = "Harem",
		["historical"] = "Historical",
		["horror"] = "Horror",
		["hot-light-novels"] = "Hot Light Novel",
		["josei"] = "Josei",
		["manhua"] = "Manhua",
		["martial-arts"] = "Martial Arts",
		["mature"] = "Mature",
		["mecha"] = "Mecha",
		["mystery"] = "Mystery",
		["one-shot"] = "One shot",
		["psychological"] = "Psychological",
		["romance"] = "Romance",
		["school-life"] = "School Life",
		["sci-fi"] = "Sci-fi",
		["seinen"] = "Seinen",
		["shoujo"] = "Shoujo",
		["shoujo-ai"] = "Shoujo Ai",
		["shounen"] = "Shounen",
		["shounen-ai"] = "Shounen Ai",
		["slice-of-life"] = "Slice of Life",
		["soft-yaoi"] = "Soft Yaoi",
		["soft-yuri"] = "Soft Yuri",
		["sports"] = "Sports",
		["supernatural"] = "Supernatural",
		["tragedy"] = "Tragedy",
		["wuxia"] = "Wuxia",
		["xianxia"] = "Xianxia",
		["xuanhuan"] = "Xuanhuan",
		["yaoi"] = "Yaoi",
		["yuri"] = "Yuri"
	},
})
