-- {"id":394,"version":"1.0.0","author":"TechnoJo4","repo":""}
return Require("Madara")("https://readnovelforlife.com", {
	id = 394,
	name = "ReadNovelForLife",
	imageURL = "https://readnovelforlife.com/wp-content/uploads/2019/12/Logo-1-e1570608260730.png",
	genres = {
        ["action"] = "Action",
        ["adventure"] = "Adventure",
        ["comedy"] = "Comedy",
        ["drama"] = "Drama",
        ["ecchi"] = "Ecchi",
        ["fantasy"] = "Fantasy",
        ["gender-bender"] = "Gender Bender",
        ["harem"] = "Harem",
        ["historical"] = "Historical",
        ["horror"] = "Horror",
        ["josei"] = "Josei",
        ["martial-arts"] = "Martial Arts",
        ["mature"] = "Mature",
        ["mecha"] = "Mecha",
        ["mystery"] = "Mystery",
        ["psychological"] = "Psychological",
        ["romance"] = "Romance",
        ["school-life"] = "School Life",
        ["sci-fi"] = "Sci-fi",
        ["seinen"] = "Seinen",
        ["shoujo"] = "Shoujo",
        ["shounen"] = "Shounen",
        ["slice-of-life"] = "Slice of Life",
        ["smut"] = "Smut",
        ["sports"] = "Sports",
        ["supernatural"] = "Supernatural",
        ["tragedy"] = "Tragedy",
        ["wuxia"] = "Wuxia",
        ["xianxia"] = "Xianxia",
        ["xuanhuan"] = "Xuanhuan",
        ["yaoi"] = "Yaoi"
    },
	hasSearch = false,
	appendToSearchFilters = function()
		return {}
	end,
})