-- {"id":586,"version":"1.0.0","author":"TechnoJo4","repo":""}

return Require("Madara")("https://vipnovel.com", {
	id = 586,
	name = "VipNovel",
	imageURL = "https://vipnovel.com/wp-content/uploads/2017/10/coollogo_com-1630861.png",
	novelListingURLPath = "vipnovel",
	genres = {
		["action"] = "Action",
		["adult"] = "Adult",
		["adventure"] = "Adventure",
		["bl"] = "BL",
		["comedy"] = "Comedy",
		["drama"] = "Drama",
		["ecchi"] = "Ecchi",
		["fantasy"] = "Fantasy",
		["gender-bender"] = "Gender Bender",
		["harem"] = "Harem",
		["historical"] = "Historical",
		["horror"] = "Horror",
		["josei"] = "Josei",
		["lgbt"] = "LGBT+",
		["martial-arts"] = "Martial Arts",
		["mature"] = "Mature",
		["mecha"] = "Mecha",
		["mystery"] = "Mystery",
		["psychological"] = "Psychological",
		["romance"] = "Romance",
		["school-life"] = "School Life",
		["sci-fi"] = "Sci-fi",
		["seinen"] = "Seinen",
		["shoujo"] = "Shoujo",
		["shounen"] = "Shounen",
		["slice-of-life"] = "Slice of Life",
		["smut"] = "Smut",
		["sports"] = "Sports",
		["supernatural"] = "Supernatural",
		["tragedy"] = "Tragedy",
		["video-games"] = "Video Games",
		["wuxia"] = "Wuxia",
		["xianxia"] = "Xianxia",
		["xuanhuan"] = "Xuanhuan",
		["yaoi"] = "Yaoi",
		["yuri"] = "Yuri"
	}
})
